
        
name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: windows-latest
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: docker check
        run: docker ps
      
          
