# This is a basic workflow to help you get started with Actions

name: Getting Started

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 1. Disc Space before build
        run: df
      
      - name: 2. Checkout the main branch
        uses: actions/checkout@v3
      
      - name: 3. setup the python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          
      - name: 4. Log build the tool versions
        run: |
          git --version
          gradle --version
      
      - name: 5. After build disc space
        run: df
      
          
