name: workflow_qc

on:
 workflow_dispatch:
    inputs: 
      workflow2_name:
        description: 'Workflow2 Name for Triggering'
        required: true
        default: 'workflow'
      
      workflow2_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: 'SOliyhan'
      
      workflow2_repo_github:
        description: 'GitHub Repository Name'
        required: true
        default: 'RockPaperScissors'

jobs:
  build:

    runs-on: windows-latest
    env: 
      pat_token: ${{ secrets.PAT_TOKEN }}
      payload_Baseline_Number: "BSL_001"
      payload_Baseline_Revision: "zsfdgsdbgngffdwdx1dxvv2"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        where python
        cd "$GITHUB_WORKSPACE"
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv install
        
    - name: Trigger the Workflow
      run: |
         python workflow_trigger.py ${{ env.pat_token }}  ${{ github.event.inputs.workflow2_github_account}}  ${{ github.event.inputs.workflow2_repo_github}} ${{ github.event.inputs.workflow2_name}} ${{ env.payload_Baseline_Number }} ${{ env.payload_Baseline_Revision }}
    

 
